# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-17 10:18
from __future__ import unicode_literals

from django.db import migrations, models
import formfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('meta_info', formfield.fields.ModelFormField(blank=True, null=True)),
            ],
        ),
    ]
